// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ComponentsCommunication: typeof import('./src/components/composition-api/components-communication/ComponentsCommunication.vue')['default']
    CompositionPropsDemo: typeof import('./src/components/composition-api/components-communication/props/CompositionPropsDemo.vue')['default']
    EmitParent: typeof import('./src/components/options-api/components-communication/emit/EmitParent.vue')['default']
    EmitParentComposition: typeof import('./src/components/composition-api/components-communication/emit/EmitParentComposition.vue')['default']
    EmitParentCpn: typeof import('./src/components/options-api/components-communication/emit/EmitParentCpn.vue')['default']
    EmitParentOptions: typeof import('./src/components/options-api/components-communication/emit/EmitParentOptions.vue')['default']
    EmitSub: typeof import('./src/components/options-api/components-communication/emit/EmitSub.vue')['default']
    EmitSubComposition: typeof import('./src/components/composition-api/components-communication/emit/EmitSubComposition.vue')['default']
    EmitSubCpn: typeof import('./src/components/options-api/components-communication/emit/EmitSubCpn.vue')['default']
    EmitSubOptions: typeof import('./src/components/options-api/components-communication/emit/EmitSubOptions.vue')['default']
    OptionsComponentsCommunication: typeof import('./src/components/options-api/components-communication/OptionsComponentsCommunication.vue')['default']
    OptionsPropsDemo: typeof import('./src/components/options-api/components-communication/props/OptionsPropsDemo.vue')['default']
    ParentComponent: typeof import('./src/components/composition-api/components-communication/props/ParentComponent.vue')['default']
    ParentEmitComponent: typeof import('./src/components/options-api/components-communication/emit/ParentEmitComponent.vue')['default']
    ParentPropsComponent: typeof import('./src/components/options-api/components-communication/props/ParentPropsComponent.vue')['default']
    Props: typeof import('./src/components/options-api/components-communication/props.vue')['default']
    PropsDemo: typeof import('./src/components/composition-api/components-communication/PropsDemo.vue')['default']
    PropsParentComponent: typeof import('./src/components/composition-api/components-communication/props/PropsParentComponent.vue')['default']
    PropsParentComposition: typeof import('./src/components/composition-api/components-communication/props/PropsParentComposition.vue')['default']
    PropsParentOptions: typeof import('./src/components/options-api/components-communication/props/PropsParentOptions.vue')['default']
    PropsSubComponent: typeof import('./src/components/composition-api/components-communication/props/PropsSubComponent.vue')['default']
    PropsSubComposition: typeof import('./src/components/composition-api/components-communication/props/PropsSubComposition.vue')['default']
    PropsSubOptions: typeof import('./src/components/options-api/components-communication/props/PropsSubOptions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubComponent: typeof import('./src/components/composition-api/components-communication/props/SubComponent.vue')['default']
    SubEmitComponent: typeof import('./src/components/options-api/components-communication/emit/SubEmitComponent.vue')['default']
    SubPropsComponent: typeof import('./src/components/options-api/components-communication/props/SubPropsComponent.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}

export { }
